name: Release
on:
  release:
    types: [published]
jobs:
  release_zip_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          yq e -P -o=json \
            -i ".version = \"${version}\"" \
            "${{ github.workspace }}/custom_components/homeconnect_ws/manifest.json"
      - run: |
          cd ${{ github.workspace }}/custom_components/homeconnect_ws
          zip homeconnect_ws.zip -r ./
      - uses: softprops/action-gh-release@v2.5.0
        with:
          files: ${{ github.workspace }}/custom_components/homeconnect_ws/homeconnect_ws.zip
